# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 15:28
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161008_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='owner',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=api.models.contact_default, on_delete=models.SET(api.models.contact_default), to='api.User'),
        ),
    ]
