# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161008_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='command',
            field=models.CharField(choices=[(b'1', b'TakePhoto'), (b'2', b'Shutdown'), (b'3', b'Activate')], default=b'TakePhoto', max_length=15),
        ),
    ]
